Toggle menu
QueenterJuma/QueenterJuma-Responsive-Porfolio.github.io pull request #6
Opened 2022-11-22 12:39 UTC by QueenterJuma

## What does this PR do?
This PR is raised to create a Portfolio using a Mobile template from Figma
##Description of the task to be completed
 [ x] Build a hamburger menu which can be toggled
 [x] Use a mobile Figma design.
 [x] Use images and backgrounds to enhance the look of the website
 [x] Use the [HTML&CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css)
 
## How should it be tested
Clone the repository
```
git clone https://github.com/QueenterJuma/Portfolio_1/pulls 
```
Navigate to the folder
```
cd repo-name
```
Checkout the branch
```
git checkout branch_accecibility
```
#### Thanks for reviewing my PR

2022-11-22 12:58 UTC, ha-manel reviewed
# STATUS: INVALID 🔴 
Hi Team
I'm sure you put a lot of effort into this project but this PR is invalid because you didn't setup `Eslint` linters for this project 😓  

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-22 14:21 UTC, Munsa1 requested changes
Hi @QueenterJuma, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._
- [ ] It is a requirement that we use the newly updated `Readme` file. [Follow this link](https://github.com/microverseinc/readme-template/blob/master/README.md)
#### Your Current Readme File Is Outdated
![image](https://user-images.githubusercontent.com/81932478/203337779-531150ba-1fd3-4e1f-9b85-10cbca0accf3.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-22 14:21 UTC, Munsa1 commented on script.js
>      menuOpen = false;
- [ ] The links in the mobile menu should redirect the user to the appropriate section of the mobile view when clicked. Kindly do so. 
For example when the user clicks the `Portfolio` link it should go to the top of the page, when the user clicks the `About Me` page it should take the user to the about me section and when the `Contact` link is clicked it should take the user to the contact form.

![image](https://user-images.githubusercontent.com/81932478/203335219-5ac738d4-2f1e-4662-9851-769de43944b1.png)

- [ ] The mobile view should also cover the whole mobile view for user experience unlike the current situation where, if the the user scrolls down, the menu remains at the top. Using a `position: fixed` property on the mobile view parent container fixes this
![image](https://user-images.githubusercontent.com/81932478/203336777-1e2884c4-77db-4708-b25e-320defc5c8fe.png)

2022-11-23 12:42 UTC, HAMMAS-SALEEM requested changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @egichuhis, @QueenterJuma :wave:

Great work on implementing the requirements. Your project is complete. :blush:
There is nothing else to say about your project. :+1:


## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Linters
✔️ Following requirements

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-23 12:56 UTC, merged